### ISSUE TITLE
Server Crashing due to timeout

### ISSUE THREAD

**Issue by ethgasstation** [grahamperich/ethereum-dex-prices-service#21]
Frequently crashes after running for several hour with this error:
Error: WebSocket is not open: readyState 2 (CLOSING)
    at WebSocket.ping (/home/jake/ethereum-dex-prices-service/node_modules/ws/lib/websocket.js:257:19)
    at Timeout.interval.setInterval [as _onTimeout] (/home/jake/ethereum-dex-prices-service/exchanges/AirSwap.js:182:18)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by grahamperich** [comment]
@ethgasstation thanks for the bug report. It sounds like you're using the library as a long running node process, is that right? Seems like the websocket reconnection logic is failing, I'll take a look at it when I can

**Comment by grahamperich** [comment]
Also can you let me know which commit you're running? I recently fixed a bug related to websocket timeouts

**Comment by grahamperich** [comment]
the AirSwap class no longer uses websockets in the latest version of the service, so your issue should be resolved @ethgasstation 

https://github.com/grahamperich/ethereum-dex-prices-service/pull/22
